=== javaprojectsmy/java-core-xml-jdbc/java/target/classes/com/poonia/xml/customer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://java8.com/tesco"
	xmlns:tesco="http://java8.com/tesco" elementFormDefault="qualified">
	<element name="Customers">
		<complexType>
			<sequence>
				<element ref="tesco:Customer" minOccurs="1" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>
	<element name="Customer">
		<complexType>
			<sequence>
				<element name="id" type="int" />
				<element name="name" type="string" />
				<element name="dob" type="date" />
			</sequence>
		</complexType>
	</element>

</schema>

=== javaprojectsmy/java-core-xml-jdbc/java/target/classes/com/poonia/xml/customer.xml
<?xml version="1.0" encoding="UTF-8"?>
<tesco:Customers xmlns:tesco="http://java8.com/tesco"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java8.com/tesco/customer.xsd ">
	<tesco:Customer>
		<tesco:id>1</tesco:id>
		<tesco:name>poonia</tesco:name>
		<tesco:dob>2001-01-01</tesco:dob>
	</tesco:Customer>
	<tesco:Customer>
		<tesco:id>1</tesco:id>
		<tesco:name>aman</tesco:name>
		<tesco:dob>2001-01-01</tesco:dob>
	</tesco:Customer>
	<tesco:Customer>
		<tesco:id>1</tesco:id>
		<tesco:name>vikash</tesco:name>
		<tesco:dob>2001-11-01</tesco:dob>
	</tesco:Customer>
</tesco:Customers>
